# Generated by Django 5.2.8 on 2025-11-24 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='slug',
            field=models.SlugField(default='-'),
            preserve_default=False,
        ),
    ]
