# Generated by Django 5.2.8 on 2025-11-27 15:48
from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_customer_store_custo_last_na_e6a359_idx_and_more'),  # keep whatever was there
    ]

    operations = [
        migrations.RunSQL(
            """
            INSERT INTO store_collection (title)
            VALUES ('collection1')
            """,
            """
            DELETE FROM store_collection
            WHERE title = 'collection1'
            """
        )
    ]
