# Generated by Django 5.2.8 on 2025-11-28 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ('store', '0003_address_zip'),
]



    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
